### ISSUE TITLE
21日ステークホルダーミーティング準備・作戦会議

### ISSUE THREAD

**Issue by yoshihiro-maeda-cc** [nri-3-bulbasaur/menzaifu#2]

**Comment by yoshihiro-maeda-cc** [comment]
15分
- チーム 5分
- QA、FB 10分

チームの報告で言うべきこと
- フィードバックの内容とそれに対する解決方法
- 実際に今開発がどれくらい進んでいるか

**Comment by talkeyboid** [comment]
### Masatakaさん
- Q. ユーザペルソナを一言でいうなら？
 - A. 現状維持で問題の無いユーザのみを対象とする
   - ペルソナの定義とコンセプトの連携は問題無さそう
- コンセプトとUI/UXの整合性が取れていないのでは？
- 飲食店APIは既存のものはある。検討してみても良いかも
### Hiroさん
- スプリントバックログがP3-5だと思うが、プロダクトバックログ＋ユーザストーリーが無いように見える
 - ユーザストーリーを実現するために必要なスプリントの範囲を決める…という流れとすると、ユーザの課題解決に有用と思われる
 - また、今後のミーティング次第では、スプリント2-3の内容が変更されることもあるので、その意味でもユーザストーリーを主軸に置いて取捨選択を行ったほうが良い（書記注：意訳です）
- UI/UX周りの感触・評価を確かめる方法の確立がアジャイル開発の肝になる
 - プロトタイプを作成し、いち早くローンチすることが重要では？
