### ISSUE TITLE
FoodTypeテーブル登録

### ISSUE THREAD

**Issue by talkeyboid** [nri-3-bulbasaur/menzaifu#33]

**Comment by rnakamura-nris** [comment]
登録済（通常：5 ＋ テスト用：6）

**Comment by rnakamura-nris** [comment]
@yoshihiro-maeda-cc ( @lalatoki  @s-tsuchida32 )  
ご指摘いただいた、テイクアウト用のカテゴリを追加しました（上位2レコード）。

![Image](https://user-images.githubusercontent.com/110962242/202973316-ca1b5be5-ea44-473e-996e-7feee187aec5.png)
