### ISSUE TITLE
ポイント消化時に「免罪符」を進呈する機能

### ISSUE THREAD

**Issue by h-nakashima** [nri-3-bulbasaur/menzaifu#74]
免罪符進呈時の機能と免罪符の表示の機能でIssueを分けるかの判断はAssigneesにおまかせします。

**Comment by davidspace-star28** [comment]
TODO
・「XXXを食べるモーダル」を押下すると、ポップアップが表示されるようにする
　＜ポップアップ＞
　・文言が表示
　・×ボタン（右上）が表示
　・右下にはリンクが表示
　・（できれば）OnClickでフリー音声がでてくる
　＜免罪符進呈＞
　・ポイント消費　→　実装済
　・「免罪符枚数XXX枚」の表示（画面左上）

**Comment by t2-kawasaki-immersive** [comment]
TODO
- [x] モーダルへの食材画像表示
- [x] 検索リンクをモーダルに入れる

- [x] 免罪符枚数表示

**Comment by t2-kawasaki-immersive** [comment]
PR済み。
