### ISSUE TITLE
免罪符獲得画面の枠を調整する

### ISSUE THREAD

**Issue by h-nakashima** [nri-3-bulbasaur/menzaifu#99]
画像が小さくなっているので直す

**Comment by h-nakashima** [comment]
![image](https://user-images.githubusercontent.com/8829393/204712264-2a5f7aed-f75d-46b8-afb3-511fe18ff97d.png)

**Comment by t2-kawasaki-immersive** [comment]
画像が真ん中になるように修正。development/stagingへマージ済み。クローズ。
